[models]
space_shuttle = "https://raw.githubusercontent.com/pichiliani/ModelsOBJ/refs/heads/master/space_shuttle.obj"
suzanne = "https://s3.amazonaws.com/everse.assets/common3dmodels/OBJ/suzanne.obj"
teapot = "https://s3.amazonaws.com/everse.assets/common3dmodels/OBJ/teapot.obj"
cube = "https://raw.githubusercontent.com/garykac/3d-cubes/refs/heads/master/cube.obj"
cube-tex = "https://raw.githubusercontent.com/garykac/3d-cubes/refs/heads/master/cube-tex.obj"
lucy = "https://github.com/alecjacobson/common-3d-test-models/raw/refs/heads/master/data/lucy.obj"
spot = "https://raw.githubusercontent.com/alecjacobson/common-3d-test-models/refs/heads/master/data/spot.obj"
seashell = "https://github.com/pichiliani/ModelsOBJ/raw/refs/heads/master/seashell.obj"
tetrahedron = "https://github.com/pichiliani/ModelsOBJ/raw/refs/heads/master/tetrahedron.obj"
text = "https://raw.githubusercontent.com/ruttingerhslu/raytracer/refs/heads/main/assets/required_text.obj"
cat = "https://raw.githubusercontent.com/ruttingerhslu/raytracer/refs/heads/main/assets/cat/oiiaioooooiai_cat.obj"
