[scene]
width = 800
height = 600

[cube]
center = { x = 400.0, y = 300.0, z = -40.0 }
rotation = { x = 30.0, y = 45.0, z = 0.0 }
size = 100.0
color = 16777215  # White

[spheres]
[[spheres]]
position = { x = 350.0, y = 300.0, z = 10.0 }
radius = 100.0
color = 16711680  # Red

[[spheres]]
position = { x = 450.0, y = 300.0, z = 20.0 }
radius = 60.0
color = 65280  # Green

[[spheres]]
position = { x = 400.0, y = 214.4, z = 40.0 }
radius = 100.0
color = 255  # Blue

[lights]
[[lights]]
position = { x = 266.6667, y = 600.0, z = -200.0 }
color = 16777215  # White

[[lights]]
position = { x = 400.0, y = 300.0, z = -150.0 }
color = 16777215  # White

[[lights]]
position = { x = 0.0, y = 0.0, z = 0.0 }
color = 16777215  # White
